version = 1

[[packages]]
id = "nlohmann/json"
slug = "nlohmann_json"

[[packages]]
id = "fmtlib/fmt"
slug = "fmt"

[[packages]]
id = "madler/zlib"
slug = "zlib"

[[packages]]
id = "cliutils/CLI11"
slug = "cli11"

[[packages]]
id = "Neargye/magic_enum"
slug = "magic_enum"

[[packages]]
id = "skypjack/entt"
slug = "entt"

[[packages]]
id = "jarro2783/cxxopts"
slug = "cxxopts"

[[packages]]
id = "TartanLlama/expected"
slug = "tl_expected"

[[packages]]
id = "gabime/spdlog"
slug = "spdlog"

[[packages]]
id = "pybind/pybind11"
slug = "pybind11"

[[packages]]
id = "ericniebler/range-v3"
slug = "range_v3"

[[packages]]
id = "doctest/doctest"
slug = "doctest"

[[packages]]
id = "microsoft/GSL"
slug = "gsl"

[[packages]]
id = "Neargye/nameof"
slug = "nameof"

[[packages]]
id = "foonathan/type_safe"
slug = "type_safe"

[[packages]]
id = "martinmoene/span-lite"
slug = "span_lite"

[[packages]]
id = "martinmoene/optional-lite"
slug = "optional_lite"

[[packages]]
id = "martinmoene/string-view-lite"
slug = "string_view_lite"

[[packages]]
id = "Tessil/robin-map"
slug = "robin_map"

[[packages]]
id = "martinus/nanobench"
slug = "nanobench"
